name: "[Jonas] Fetch Vulnerability Feeds"
description: Monitors public CVE feeds for vulnerabilities affecting our tech stack (Go, TypeScript, JavaScript, Kotlin, Java, Ubuntu, Debian, AWS, GCP) and creates Linear issues for awareness

triggers:
  - manual: {}
    context:
      projects: {}

action:
  limits:
    maxParallel: 1
    maxTotal: 10
  steps:
    - task:
        command: |
          set -e

          # Calculate date range (last 2 days)
          END_DATE=$(date -u +%Y-%m-%dT%H:%M:%S.000)
          START_DATE=$(date -u -d "2 days ago" +%Y-%m-%dT%H:%M:%S.000)

          echo "Fetching CVEs published between $START_DATE and $END_DATE"

          # Fetch from NVD API (National Vulnerability Database)
          # NVD API docs: https://nvd.nist.gov/developers/vulnerabilities
          curl -s "https://services.nvd.nist.gov/rest/json/cves/2.0?pubStartDate=${START_DATE}&pubEndDate=${END_DATE}&resultsPerPage=2000" \
            -H "Accept: application/json" \
            -o /tmp/nvd-cves.json

          # Fetch from OSV (Open Source Vulnerabilities) for ecosystem-specific data
          # Query for each ecosystem we care about
          for ecosystem in "Go" "npm" "Maven" "PyPI"; do
            echo "Fetching OSV data for $ecosystem..."
            curl -s "https://api.osv.dev/v1/query" \
              -X POST \
              -H "Content-Type: application/json" \
              -d "{\"package\": {\"ecosystem\": \"$ecosystem\"}}" \
              -o "/tmp/osv-${ecosystem}.json" || true
          done

          # Fetch GitHub Security Advisories (public feed)
          curl -s "https://api.github.com/advisories?per_page=100&sort=published&direction=desc" \
            -H "Accept: application/vnd.github+json" \
            -o /tmp/github-advisories.json || true

          # Fetch CISA Known Exploited Vulnerabilities (KEV) catalog
          # These are actively exploited in the wild - highest priority
          echo "Fetching CISA KEV catalog..."
          curl -s "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json" \
            -o /tmp/cisa-kev.json || true

          # Fetch Go Vulnerability Database index
          # Official Go vulnerability data, more accurate than NVD for Go packages
          echo "Fetching Go Vulnerability Database..."
          curl -s "https://vuln.go.dev/index.json" \
            -o /tmp/go-vuln-index.json || true

          # Fetch Ubuntu Security Notices (USN) RSS feed
          echo "Fetching Ubuntu Security Notices..."
          curl -s "https://ubuntu.com/security/notices/rss.xml" \
            -o /tmp/ubuntu-usn.xml || true

          # Fetch Debian Security Tracker JSON
          echo "Fetching Debian Security Tracker..."
          curl -s "https://security-tracker.debian.org/tracker/data/json" \
            -o /tmp/debian-security.json || true

          # Fetch AWS Security Bulletins RSS
          echo "Fetching AWS Security Bulletins..."
          curl -s "https://aws.amazon.com/security/security-bulletins/feed/" \
            -o /tmp/aws-security.xml || true

          # Fetch GCP Security Bulletins
          echo "Fetching GCP Security Bulletins..."
          curl -s "https://cloud.google.com/feeds/google-cloud-security-bulletins.xml" \
            -o /tmp/gcp-security.xml || true

          echo "CVE data fetched successfully"
          echo "NVD results: $(cat /tmp/nvd-cves.json | head -c 500)"

    - agent:
        prompt: |
          Create Linear issues for new vulnerabilities affecting our stack.

          FEEDS (already fetched):
          - /tmp/nvd-cves.json, /tmp/osv-*.json, /tmp/github-advisories.json
          - /tmp/cisa-kev.json (actively exploited - always include)
          - /tmp/go-vuln-index.json, /tmp/ubuntu-usn.xml, /tmp/debian-security.json
          - /tmp/aws-security.xml, /tmp/gcp-security.xml

          FILTER TO:
          - Stack: Go, TypeScript, JavaScript, Kotlin, Java, Ubuntu, Debian, AWS, GCP
          - Severity: HIGH/CRITICAL (CVSS >= 7.0) or CISA KEV
          - Published: last 2 days

          FOR EACH VULNERABILITY:
          1. Search Linear team "Ona AI Security Engineer" for existing issue with advisory ID
          2. If not found, create issue with:
             - Title: "[Advisory] <ID>: Brief description" (ID = CVE, GHSA, USN, DSA, GO-, or vendor ID)
             - Labels: ["advisory"]

          ISSUE DESCRIPTION FORMAT:
          ```
          > **This is a vulnerability ADVISORY, not a finding. Review to determine if your codebase is affected.**

          ## Why This Was Flagged
          - [Reason: e.g., "CVSS 9.8 CRITICAL", "CISA KEV (actively exploited)", "Affects Go ecosystem"]

          ## Vulnerability Summary
          - **Advisory ID:** CVE-XXXX-XXXXX / GHSA-XXXX / USN-XXXX / GO-XXXX-XXXX (use available ID)
          - **Published:** YYYY-MM-DD
          - **CVSS Score:** X.X (CRITICAL/HIGH/MEDIUM) or "Not scored"
          - **CISA KEV:** Yes/No
          - **Source:** NVD / GitHub / OSV / Go Vuln DB / Ubuntu / Debian / AWS / GCP

          ## Affected Components
          - **Ecosystem:** Go / npm / Maven / OS / Cloud
          - **Package(s):** package-name
          - **Vulnerable Versions:** < X.Y.Z
          - **Fixed Version:** X.Y.Z (if available)

          ## Technical Details
          [Description of the vulnerability and potential impact]

          ## Detection Guidance
          1. Search for imports/dependencies on: `package-name`
          2. Check version in: go.mod / package.json / pom.xml / build.gradle
          3. Vulnerable if version matches: < X.Y.Z

          ## Remediation
          - Upgrade to version X.Y.Z or later
          - Workaround: [if available]

          ## References
          - [Link to source advisory]
          ```

          Report count of new advisories created.

    - agent:
        prompt: |
          Close advisory issues older than one week.

          1. List issues in Linear team "Ona AI Security Engineer" with label "advisory"
          2. For each issue created more than 7 days ago:
             - Add comment: "Auto-closing: advisory is over 7 days old. Reopen if still relevant."
             - Close the issue
          3. Report count of closed advisories

    - report:
        outputs:
          - key: total_cves_fetched
            title: Total CVEs Fetched
            string: {}
            prompt: |
              Count the total number of CVEs retrieved from all feeds before filtering.
              Return ONLY the integer count, nothing else.
          - key: relevant_cves
            title: Relevant CVEs (matching tech stack)
            string: {}
            prompt: |
              Count the number of CVEs that matched our target tech stack filter.
              Return ONLY the integer count, nothing else.
          - key: advisories_created
            title: Linear Advisories Created
            string: {}
            prompt: |
              Count how many new Linear advisory issues were created.
              Return ONLY the integer count, nothing else.
          - key: cve_ids
            title: CVE IDs Processed
            string: {}
            prompt: |
              List all CVE IDs that were processed and created as advisories.
              Return ONLY a comma-separated list of CVE IDs, or "none" if no advisories created.
