name: "[Jonas] Fetch Vulnerability Feeds"
description: Monitors public CVE feeds for vulnerabilities affecting our tech stack (Go, TypeScript, JavaScript, Kotlin, Java, Ubuntu, Debian, AWS, GCP) and creates Linear issues for awareness

triggers:
  - manual: {}
    context:
      projects: {}

action:
  limits:
    maxParallel: 1
    maxTotal: 10
  steps:
    - task:
        command: |
          set -e

          # Calculate date range (last 2 days)
          END_DATE=$(date -u +%Y-%m-%dT%H:%M:%S.000)
          START_DATE=$(date -u -d "2 days ago" +%Y-%m-%dT%H:%M:%S.000)

          echo "Fetching CVEs published between $START_DATE and $END_DATE"

          # Fetch from NVD API (National Vulnerability Database)
          # NVD API docs: https://nvd.nist.gov/developers/vulnerabilities
          curl -s "https://services.nvd.nist.gov/rest/json/cves/2.0?pubStartDate=${START_DATE}&pubEndDate=${END_DATE}&resultsPerPage=2000" \
            -H "Accept: application/json" \
            -o /tmp/nvd-cves.json

          # Fetch from OSV (Open Source Vulnerabilities) for ecosystem-specific data
          # Query for each ecosystem we care about
          for ecosystem in "Go" "npm" "Maven" "PyPI"; do
            echo "Fetching OSV data for $ecosystem..."
            curl -s "https://api.osv.dev/v1/query" \
              -X POST \
              -H "Content-Type: application/json" \
              -d "{\"package\": {\"ecosystem\": \"$ecosystem\"}}" \
              -o "/tmp/osv-${ecosystem}.json" || true
          done

          # Fetch GitHub Security Advisories (public feed)
          curl -s "https://api.github.com/advisories?per_page=100&sort=published&direction=desc" \
            -H "Accept: application/vnd.github+json" \
            -o /tmp/github-advisories.json || true

          echo "CVE data fetched successfully"
          echo "NVD results: $(cat /tmp/nvd-cves.json | head -c 500)"

    - agent:
        prompt: |
          You are a security intelligence analyst monitoring public vulnerability feeds.

          CONTEXT:
          - This automation runs periodically to track new CVE publications
          - You are creating AWARENESS issues, not findings from code scans
          - Each issue describes a vulnerability that MAY affect our systems
          - Engineers will use these issues to assess if their codebases are impacted

          TARGET TECH STACK (filter vulnerabilities to these only):
          - Languages: Golang, TypeScript, JavaScript, Kotlin, Java
          - Operating Systems: Ubuntu Linux, Debian Linux
          - Cloud Providers: Amazon Web Services (AWS), Google Cloud Platform (GCP)

          TASK:

          1. Read the fetched CVE data from:
             - /tmp/nvd-cves.json (NVD feed)
             - /tmp/osv-*.json (OSV ecosystem feeds)
             - /tmp/github-advisories.json (GitHub advisories)

          2. Filter to vulnerabilities that:
             - Were published within the last 2 days
             - Affect our target tech stack (check CPE strings, ecosystem tags, affected packages)
             - Have severity HIGH or CRITICAL (CVSS >= 7.0) OR are widely discussed

          3. For each relevant vulnerability:
             a. Search Linear team "Ona AI Security Engineer" for existing issue with this CVE ID using list_issues
             b. If NOT found, create a new issue using create_issue with:
                - Team: "Ona AI Security Engineer"
                - Labels: ["saf-advisory"]
                - Title format: "[Advisory] CVE-XXXX-XXXXX: Brief description"

          ISSUE DESCRIPTION FORMAT (include ALL details needed for impact assessment):
          ```
          > **This is a vulnerability ADVISORY, not a finding. Review to determine if your codebase is affected.**

          ## Vulnerability Summary
          - **CVE ID:** CVE-XXXX-XXXXX
          - **Published:** YYYY-MM-DD
          - **CVSS Score:** X.X (CRITICAL/HIGH/MEDIUM)
          - **Attack Vector:** Network/Local/Adjacent

          ## Affected Components
          - **Ecosystem:** Go / npm / Maven / etc.
          - **Package(s):** package-name
          - **Vulnerable Versions:** < X.Y.Z
          - **Fixed Version:** X.Y.Z (if available)

          ## Technical Details
          [Description of the vulnerability, attack scenario, and potential impact]

          ## Detection Guidance
          To check if your codebase is affected:
          1. Search for imports/dependencies on: `package-name`
          2. Check version in: go.mod / package.json / pom.xml / build.gradle
          3. Vulnerable if version matches: < X.Y.Z

          ## Remediation
          - Upgrade to version X.Y.Z or later
          - Workaround: [if available]

          ## References
          - NVD: https://nvd.nist.gov/vuln/detail/CVE-XXXX-XXXXX
          - Advisory: [link to vendor advisory]
          - GitHub Advisory: [link if available]

          ---
          *Auto-generated from CVE feed on YYYY-MM-DD*
          ```

          IMPORTANT:
          - Title must start with "[Advisory]" to distinguish from scan findings
          - Always include the "saf-advisory" label
          - Include enough detail for an engineer to grep/search their codebase
          - List specific package names, import paths, and version constraints
          - Skip vulnerabilities already tracked (check list_issues first)

          LINEAR TOOLS:
          - list_issues: search existing issues (team: "Ona AI Security Engineer", query: CVE ID)
          - create_issue: create new advisory issues (team: "Ona AI Security Engineer", labels: ["saf-advisory"])

          After processing, report how many new advisories were created.

    - report:
        outputs:
          - key: total_cves_fetched
            title: Total CVEs Fetched
            string: {}
            prompt: |
              Count the total number of CVEs retrieved from all feeds before filtering.
              Return ONLY the integer count, nothing else.
          - key: relevant_cves
            title: Relevant CVEs (matching tech stack)
            string: {}
            prompt: |
              Count the number of CVEs that matched our target tech stack filter.
              Return ONLY the integer count, nothing else.
          - key: advisories_created
            title: Linear Advisories Created
            string: {}
            prompt: |
              Count how many new Linear advisory issues were created.
              Return ONLY the integer count, nothing else.
          - key: cve_ids
            title: CVE IDs Processed
            string: {}
            prompt: |
              List all CVE IDs that were processed and created as advisories.
              Return ONLY a comma-separated list of CVE IDs, or "none" if no advisories created.
