name: "[Jonas] Fix Security Issue"
description: Fixes a random Linear finding for the current repository
triggers:
  - manual: {}
    context:
      projects: {}

action:
  limits:
    maxParallel: 1
    maxTotal: 10
  steps:
    - agent:
        prompt: |
          Select a vulnerability finding to fix.

          1. Fetch issues from Linear (team: "Ona AI Security Engineer", label: "finding")
          2. Filter to issues containing "{{repository_name}}" in title/description
          3. If none found, report "No findings for {{repository_name}}" and STOP
          4. Select one at random and report: "Selected [identifier]: [title]"

          If the list_issue tool returns an empty list, it could be that filtering by team or lable is brioken. In this case, query by repo name.

          Extract: issue_id, identifier, CVE ID, affected package/version, fixed version, file locations.

    - agent:
        prompt: |
          Check if the selected vulnerability is already fixed.

          1. Read affected files and dependency files for the vulnerable version
          2. Search PRs (open and merged) for the CVE ID or package name

          If ALREADY FIXED:
          - Identify the fixing PR
          - Report: "Already fixed by PR #[number]"

          If NEEDS FIX:
          - Determine fix type: dependency_upgrade, code_migration, config_change, or code_replacement
          - Identify files to modify and target version
          - Report: "Needs fix: [description]"

    - agent:
        prompt: |
          Handle the vulnerability based on fix status.

          If ALREADY FIXED:
          - Comment on Linear issue documenting the existing PR and evidence
          - Report: "Linked existing PR to [identifier]"
          - STOP (do not create new PR)

          If NEEDS FIX:
          - Implement the fix (update dependencies, migrate code, etc.)
          - Run tests if available
          - Stage changes with git add
          - Report: "Implemented: [description]"

    - pullRequest:
        branch: jonas/{{linear_issue_id}}-fix
        description: Automated security fix by Ona Agent.
        draft: false
        title: "fix: security vulnerability remediation"

    - agent:
        prompt: |
          Document the completed fix.

          If existing PR was linked (no new PR created):
          - Report summary and STOP

          If new fix was implemented:
          - Comment on Linear issue with: change description, files modified, test results
          - Generate summary with repository, issue, changes, and next steps

    - report:
        outputs:
          - key: action_taken
            title: Action Taken
            string: {}
            prompt: |
              Return ONLY: LINKED_EXISTING_PR, IMPLEMENTED_FIX, or NO_ISSUES_FOUND
          - key: issue_identifier
            title: Issue Processed
            string: {}
            prompt: Return ONLY the Linear issue identifier, or "none"
          - key: fix_type
            title: Fix Type
            string: {}
            prompt: |
              Return ONLY: dependency_upgrade, code_migration, config_change, code_replacement, or "n/a"
          - key: files_modified
            title: Files Modified
            string: {}
            prompt: |
              Return ONLY comma-separated file paths, or "none"
